robot_test_name_list = [
    '1. Z STAGE SUBASSEMBLY TEST',
    '2. DIAGNOSTICS & SERIAL NUMBER PROGRAMMING',
    '3. DIAGNOSTICS FINISHED',
    '4. TESTS USING JOGGING SCRIPT',
    '5. GANTRY STRESS TEST',
    '6. XY BELT CALIBRATION',
    '7. SOFTWARE UPDATE',
    '8. QC PROTOCOL',
    '9. SHIPPING FIRMWARE'
]

ch1_pipette_test_name_list = [
    '1. CURRENT & SPEED TEST',
    '2. DIAGNOSTICS',
    '3. GRAVIMETRIC TEST',
    '4. SHIPPING FIRMWARE',
]

ch8_pipette_test_name_list = [
    '1. CURRENT & SPEED TEST',
    '2. DIAGNOSTICS',
    '3. GRAVIMETRIC TEST',
    '4. SHIPPING FIRMWARE',
]

ch96_pipette_p1000_test_name_list = [
    '1. DIAGNOSTICS AND SERIAL NUMBER TOUCHPOINT',
    '2. PROTOCOL TEST',
    '3. PHOTOMETRIC TOUCHPOINT',
    '4. GRAVIMETRIC TOUCHPOINT',
    '5. SHIPPING FIRMWARE TOUCHPOINT',
]

ch96_pipette_p200_test_name_list = [
    '1. DIAGNOSTICS AND SERIAL NUMBER TOUCHPOINT',
    '2. DROPOUT & PROTOCOL TEST TOUCHPOINT',
    '3. PHOTOMETRIC TOUCHPOINT',
    '4. GRAVIMETRIC TOUCHPOINT',
    '5. PREHEATING TOUCHPOINT',
    '6. BASELINE & DILUENT FILLING TOUCHPOINT',
    '7. SHIPPING FIRMWARE TOUCHPOINT',
]

gripper_test_name_list = [
    '1. DIAGNOSTICS SOFTWARE FIRMWARE',
    '2. QC PROTOCOL',
    '3. SHIPPING SOFTWARE FIRMWARE',
]