LABWARE_DEF_JSON = {
    "ordering": [["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1"], ["A2", "B2", "C2", "D2"], ["A3", "B3", "C3"]],
    "brand": {"brand": "Fluorescence", "brandId": ["Fluorescence"]},
    "metadata": {"displayName": "Fluorescence_tuberack_2ul", "displayCategory": "tubeRack", "displayVolumeUnits": "µL",
                 "tags": []}, "dimensions": {"xDimension": 127.75, "yDimension": 85.5, "zDimension": 124.35}, "wells": {
        "A1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 77.6,
               "z": 6.85},
        "B1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 67.6,
               "z": 6.85},
        "C1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 57.6,
               "z": 6.85},
        "D1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 47.6,
               "z": 6.85},
        "E1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 37.6,
               "z": 6.85},
        "F1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 27.6,
               "z": 6.85},
        "G1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 17.6,
               "z": 6.85},
        "H1": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 69, "y": 7.6,
               "z": 6.85},
        "A2": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 88, "y": 77.6,
               "z": 6.85},
        "B2": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 88, "y": 50,
               "z": 6.85},
        "C2": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 88, "y": 30,
               "z": 6.85},
        "D2": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 88, "y": 10,
               "z": 6.85},
        "A3": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 107, "y": 77.6,
               "z": 6.85},
        "B3": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 107, "y": 67.6,
               "z": 6.85},
        "C3": {"depth": 117.5, "totalLiquidVolume": 2, "shape": "circular", "diameter": 10, "x": 107, "y": 57.6,
               "z": 6.85}}, "groups": [{"brand": {"brand": "Fluorescence", "brandId": ["Fluorescence"]},
                                        "metadata": {"wellBottomShape": "u", "displayCategory": "tubeRack"},
                                        "wells": ["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1", "A2", "B2", "C2",
                                                  "D2", "A3", "B3", "C3"]}],
    "parameters": {"format": "irregular", "quirks": [], "isTiprack": false, "isMagneticModuleCompatible": false,
                   "loadName": "fluorescence_24_tuberack_2ul"}, "namespace": "custom_beta", "version": 1,
    "schemaVersion": 2, "cornerOffsetFromSlot": {"x": 0, "y": 0, "z": 0}}
