name: Build Executables

# 什么时候触发
on:
  push:
    branches: [leveling]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --package productions-hardwares --group build

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          uv run --package productions-hardwares pyinstaller --onefile \
            --name productions-hardwares \
            --hidden-import "cli.__version__" \
            --hidden-import "leveling_testing.config" \
            --hidden-import "leveling_testing.type" \
            --hidden-import "leveling_testing.model.base" \
            --hidden-import "leveling_testing.report.report" \
            --hidden-import "opentonrs_api.hardware_control.hardware_control" \
            --hidden-import "opentonrs_api.protocol.protocol_context" \
            --hidden-import "opentonrs_api.maintenance_api.maintenance_run" \
            --hidden-import "cli.interface.operator_prompts" \
            --hidden-import "leveling_testing.reading_laser" \
            --add-data "apps/hardwares/src/leveling_testing/leveling_config.json:leveling_testing" \
            apps/hardwares/src/cli/main.py
          ls -lh dist/

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          uv run --package productions-hardwares pyinstaller --onefile `
            --name productions-hardwares `
            --hidden-import "cli.__version__" `
            --hidden-import "leveling_testing.config" `
            --hidden-import "leveling_testing.type" `
            --hidden-import "leveling_testing.model.base" `
            --hidden-import "leveling_testing.report.report" `
            --hidden-import "opentonrs_api.hardware_control.hardware_control" `
            --hidden-import "opentonrs_api.protocol.protocol_context" `
            --hidden-import "opentonrs_api.maintenance_api.maintenance_run" `
            --hidden-import "cli.interface.operator_prompts" `
            --hidden-import "leveling_testing.reading_laser" `
            --add-data "apps/hardwares/src/leveling_testing/leveling_config.json;leveling_testing" `
            apps/hardwares/src/cli/main.py
          dir dist/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: productions-hardwares-${{ runner.os }}
          path: dist/
